#pragma once

enum Game_State {
    BOOT_INIT,
    GAME_INIT,
    TITLE_SCREEN,
    LOAD_DEMO_STAGE,
    LOAD_STAGE,
    STANDBY_PLAY,
    NORMAL_PLAY,
    LOSE_LIFE,
    STAGE_CLEAR,
    WIN,
    BONUS_STATE_HANDLER,
    GAME_OVER_CHECK,
    PAUSE
};

enum Game_Event {
    NONE = 0,
    EXTRA_LIFE = 1,
    WHITE_BRICK_HIT = 2,
    UNBREAKABLE_BRICK_HIT = 3,
    PADDLE_COLLISION = 4,
    LIGHT_GREY_BRICK_HIT = 5,
    DARK_GREY_BRICK_HIT = 6,
    BALL_LAUNCHED = 7,
    BONUS_COUNTDOWN = 8,
    MARIO_JUMP = 9,
    NO_LIVES_LEFT = 10,
    CEILING_COLLISION = 11,  // except during bonus levels
    WALL_COLLISION = 12
};

enum Game_Track {
    NO_TRACK,
    TITLE_TRACK,
    START_TRACK,
    GAME_OVER_TRACK,
    PAUSE_TRACK,
    STAGE_COMPLETE_TRACK,
    BONUS_STAGE_TRACK,
    BONUS_STAGE_FAST_TRACK,
    BONUS_STAGE_START_TRACK,
    BONUS_STAGE_LOSE_TRACK,
    BONUS_STAGE_WIN_TRACK,
    BRICK_SCROLLDOWN_SFX,
    GAME_WIN_TRACK
};

enum Brick_Type {
    NO_BRICK = 0,
    WHITE_BRICK = 1,
    LIGHT_GREY_BRICK = 2,
    DARK_GREY_BRICK = 3,
    UNBREAKABLE_BRICK = 4
};

enum SFX_Envelope {
    PADDLE_SFX_ENV_5_4 = 0,
    PADDLE_SFX_ENV_3 = 1,
    PADDLE_SFX_ENV_2 = 2,
    WHITE_BRICK_SFX_ENV_5_4 = 3,
    WHITE_BRICK_SFX_ENV_3 = 4,
    WHITE_BRICK_SFX_ENV_2 = 5,
    UNBREAKABLE_BRICK_SFX_ENV_5 = 6,
    UNBREAKABLE_BRICK_SFX_ENV_4 = 7,
    UNBREAKABLE_BRICK_SFX_ENV_3 = 8,
    UNBREAKABLE_BRICK_SFX_ENV_2 = 9,
    EXTRA_LIFE_SFX_ENV_7 = 10,
    EXTRA_LIFE_SFX_ENV_6 = 11,
    EXTRA_LIFE_SFX_ENV_5 = 12,
    EXTRA_LIFE_SFX_ENV_4 = 13,
    EXTRA_LIFE_SFX_ENV_3 = 14,
    EXTRA_LIFE_SFX_ENV_2 = 15,
    LIGHT_GREY_BRICK_SFX_ENV_5_4 = 16,
    LIGHT_GREY_BRICK_SFX_ENV_3 = 17,
    LIGHT_GREY_BRICK_SFX_ENV_2 = 18,
    DARK_GREY_BRICK_SFX_ENV_5_4 = 19, 
    DARK_GREY_BRICK_SFX_ENV_3 = 20,
    DARK_GREY_BRICK_SFX_ENV_2 = 21,
    BALL_LAUNCH_SFX_ENV_4 = 22,
    BALL_LAUNCH_SFX_ENV_3 = 23,
    BALL_LAUNCH_SFX_ENV_2 = 24,
    POINT_COUNTDOWN_SFX_ENV_5 = 25,
    POINT_COUNTDOWN_SFX_ENV_4 = 26,
    POINT_COUNTDOWN_SFX_ENV_3 = 27,
    POINT_COUNTDOWN_SFX_ENV_2 = 28
};